In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Downloads/2019 Winter Data Science Intern Challenge Data Set - Sheet1.csv')

In [3]:
df.count()

order_id          5000
shop_id           5000
user_id           5000
order_amount      5000
total_items       5000
payment_method    5000
created_at        5000
dtype: int64

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   order_id        5000 non-null   int64 
 1   shop_id         5000 non-null   int64 
 2   user_id         5000 non-null   int64 
 3   order_amount    5000 non-null   int64 
 4   total_items     5000 non-null   int64 
 5   payment_method  5000 non-null   object
 6   created_at      5000 non-null   object
dtypes: int64(5), object(2)
memory usage: 273.6+ KB


In [5]:
#checking for any duplicates
df['order_id'].duplicated().any()

False

In [6]:
#Highest number of a sales a shop has is 68
df['shop_id'].value_counts().max()

68

In [7]:
#Lowest number of a sales a shop has is 35
df['shop_id'].value_counts().min()

35

In [8]:
#Average number of a sales a shop has is 50
df['shop_id'].value_counts().mean()

50.0

In [9]:
#Shops with most sales
df['shop_id'].value_counts()[(df['shop_id'].value_counts() > 60)]

53    68
71    66
19    64
13    63
89    61
Name: shop_id, dtype: int64

In [10]:
#Average amount for an order. This seems high for what an average customer would spend on a order for sneakers.
df['order_amount'].mean()

3145.128

In [11]:
#My initial guess is outliers so I will check for thoose
#First lets see what the min order amount is
#90 seems a fair price for a sneaker order so I do not think that their are any outliers with very low price
df['order_amount'].min()


90

In [12]:
#Now lets check for the max order price 
#70400 seems high for a sneaker order, but again that is not the price for one sneaker. It can be for a very big sneaker order
df['order_amount'].max()

704000

In [13]:
#The median seems more reasonable
#Median is better if teh data is skewed. 
#There can be some shops with highorder amounts that can skew the results.
#Some shops can be selling more items. Their price per sneaker can be high. Or there can be input error which can craete outliers
df['order_amount'].median()

284.0

In [14]:
df['order_amount'].mode()

0    153
dtype: int64

In [21]:
#Shops with very high order amounts
df['shop_id'][df['order_amount'] > 5000].unique()

array([42, 78])

In [15]:
#Lets look at the price per sneaker for every shop
df['sneaker_price'] = df['order_amount'] / df['total_items']

In [15]:
#387.7 seems high to me for the average price of a sneaker. 
df['sneaker_price'].mean()

387.7428

In [16]:
# Looking at the median we can see average price for sneaker is high. 
df['sneaker_price'].median()

153.0

In [17]:
df['sneaker_price'].mode()

0    153.0
dtype: float64

In [18]:
#The highest order is 704000. Is this an error or is it the actual price? I will confirm this by looking at the sneaker price for the shop and checking if this is the same for the amount of items purchased from this shop
df['order_amount'].max()

704000

In [19]:
#Shop 42 is selling 2000 sneakers for a total of 704000. 
df.loc[df['order_amount'] == 704000]

order_id  shop_id  user_id  order_amount  total_items payment_method  \
15          16       42      607        704000         2000    credit_card   
60          61       42      607        704000         2000    credit_card   
520        521       42      607        704000         2000    credit_card   
1104      1105       42      607        704000         2000    credit_card   
1362      1363       42      607        704000         2000    credit_card   
1436      1437       42      607        704000         2000    credit_card   
1562      1563       42      607        704000         2000    credit_card   
1602      1603       42      607        704000         2000    credit_card   
2153      2154       42      607        704000         2000    credit_card   
2297      2298       42      607        704000         2000    credit_card   
2835      2836       42      607        704000         2000    credit_card   
2969      2970       42      607        704000         2000    credit_card   
3332      3333       42      607        704000         2000    credit_card   
4056      4057       42      607        704000         2000    credit_card   
4646      4647       42      607        704000         2000    credit_card   
4868      4869       42      607        704000         2000    credit_card   
4882      4883       42      607        704000         2000    credit_card   

              created_at  sneaker_price  
15    2017-03-07 4:00:00          352.0  
60    2017-03-04 4:00:00          352.0  
520   2017-03-02 4:00:00          352.0  
1104  2017-03-24 4:00:00          352.0  
1362  2017-03-15 4:00:00          352.0  
1436  2017-03-11 4:00:00          352.0  
1562  2017-03-19 4:00:00          352.0  
1602  2017-03-17 4:00:00          352.0  
2153  2017-03-12 4:00:00          352.0  
2297  2017-03-07 4:00:00          352.0  
2835  2017-03-28 4:00:00          352.0  
2969  2017-03-28 4:00:00          352.0  
3332  2017-03-24 4:00:00          352.0  
4056  2017-03-28 4:00:00          352.0  
4646  2017-03-02 4:00:00          352.0  
4868  2017-03-22 4:00:00          352.0  
4882  2017-03-25 4:00:00          352.0

In [20]:
#Here we can see that price / sneaker  is same for different orders. So I do not think that it is a wrong entry issue.
df.loc[df['shop_id'] == 42]['sneaker_price'].unique()

array([352.])

In [21]:
#What shop sells the most expensive shoe?
#25725 seems very high for a shoe. Is it an outlier?
df['sneaker_price'].max()

25725.0

In [22]:
#Lets see which shop is selling this sneaker and if price/sneaker is same for all orders
#This will confirm is 25725 is wrong price /sneaker for one order or is it consistent with other orders
#we can see that only shop 78 sells a sneaker for 25725
df.loc[df['sneaker_price'] == 25725]['shop_id'].unique()

array([78])

In [23]:
#For different orders the price of a sneaker is same, therefore it is not a wrong entry, but instead the sneaker is very high end
df.loc[df['shop_id'] == 78]['sneaker_price'].unique()

array([25725.])

In [24]:
#There are some shops selling high end sneakers which are skewing the results.
#Lets check how many shops are selling these high end sneakers
#I am considering a sneaker above 350 a high end sneaker as median and mode for sneaker is 153

In [25]:
#Only shop 42 and 78 are selling high end sneakers
df.loc[df['sneaker_price'] > 350]['shop_id'].unique()

array([42, 78])

In [26]:
#Shop 42 sells sneakers for 352 and shop 78 sells sneakers for 25725. In this case shop 78 seems like the shop that can skew the results
df.loc[df['sneaker_price'] > 350]['sneaker_price'].unique()

array([  352., 25725.])

In [27]:
#There are 46 orders for shop 78. 
df['shop_id'][df['shop_id'] == 78 ].count()

46

In [28]:
# I am removing shop 78 from the data
df = df[df['shop_id'] != 78 ]

In [29]:
#new sneaker price mean is 152 which is close to the median. This means sneaker price is longer skewed
df['sneaker_price'].mean()

152.47557529269278

In [30]:
df['sneaker_price'].median()

153.0

In [31]:
#Average order amount is still very high and skewed. We have removed the most expensive sneaker.
#Lets investigate what eslse is skewing the result
df['order_amount'].mean()

2717.3677836092047

In [32]:
#We can see that some orders are selling 2000 sneakers. This is something that is likely skewing the average order amount
df['total_items'].unique()

array([   2,    1,    3, 2000,    4,    5,    6,    8])

In [33]:
#Shop 42 is the only shop with 2000 orders. This is skewing the results for the average order_amount
#We can either remove these or we can normalize them by converting the order amount from 2000 items to a more standard number of items such as 5. 
df.loc[df['total_items'] == 2000]

order_id  shop_id  user_id  order_amount  total_items payment_method  \
15          16       42      607        704000         2000    credit_card   
60          61       42      607        704000         2000    credit_card   
520        521       42      607        704000         2000    credit_card   
1104      1105       42      607        704000         2000    credit_card   
1362      1363       42      607        704000         2000    credit_card   
1436      1437       42      607        704000         2000    credit_card   
1562      1563       42      607        704000         2000    credit_card   
1602      1603       42      607        704000         2000    credit_card   
2153      2154       42      607        704000         2000    credit_card   
2297      2298       42      607        704000         2000    credit_card   
2835      2836       42      607        704000         2000    credit_card   
2969      2970       42      607        704000         2000    credit_card   
3332      3333       42      607        704000         2000    credit_card   
4056      4057       42      607        704000         2000    credit_card   
4646      4647       42      607        704000         2000    credit_card   
4868      4869       42      607        704000         2000    credit_card   
4882      4883       42      607        704000         2000    credit_card   

              created_at  sneaker_price  
15    2017-03-07 4:00:00          352.0  
60    2017-03-04 4:00:00          352.0  
520   2017-03-02 4:00:00          352.0  
1104  2017-03-24 4:00:00          352.0  
1362  2017-03-15 4:00:00          352.0  
1436  2017-03-11 4:00:00          352.0  
1562  2017-03-19 4:00:00          352.0  
1602  2017-03-17 4:00:00          352.0  
2153  2017-03-12 4:00:00          352.0  
2297  2017-03-07 4:00:00          352.0  
2835  2017-03-28 4:00:00          352.0  
2969  2017-03-28 4:00:00          352.0  
3332  2017-03-24 4:00:00          352.0  
4056  2017-03-28 4:00:00          352.0  
4646  2017-03-02 4:00:00          352.0  
4868  2017-03-22 4:00:00          352.0  
4882  2017-03-25 4:00:00          352.0

In [34]:
#I will be removing rows for shop 42 with 2000 items. These are likely bulk orders only specific to shop 42.
df = df[df['total_items'] != 2000]

In [35]:
df['total_items'].unique()

array([2, 1, 3, 4, 5, 6, 8])

In [36]:
df['total_items'].value_counts()

2    1816
1    1811
3     932
4     292
5      77
6       8
8       1
Name: total_items, dtype: int64

In [37]:
#Therefore after wrangling the data, the mean is 302.
df['order_amount'].mean()

302.58051448247926

In [38]:
df['order_amount'].median()

284.0